
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-happycows-f25-13
owner: ucsb-cs156-f25
repo_name: proj-happycows-f25-13
pull_requests: [{"author":{"id":"U_kgDOCE2Lig","is_bot":false,"login":"n-ornelas","name":""},"headRefName":"n-ornelas-stryker-tests","number":32,"title":"n-ornelas - Added 2 tests in CommonsCard.test.jsx to cover for failing Stryker tests","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-13/pull/32"},{"author":{"id":"U_kgDOCVHjrA","is_bot":false,"login":"yoonseo642","name":""},"headRefName":"ys-chat-frontend-pagination","number":31,"title":"Ys chat frontend pagination","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-13/pull/31"},{"author":{"id":"U_kgDOCU6U0g","is_bot":false,"login":"LemoNaCl","name":"Hao Ding"},"headRefName":"launcher-for-RecordCommonStats","number":30,"title":"Launcher for record common stats","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-13/pull/30"},{"author":{"id":"U_kgDOCsAPpQ","is_bot":false,"login":"sidushdid","name":""},"headRefName":"sidushdid-navigation-and-default-homepage-redesign","number":28,"title":"changed navigation for main page","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-13/pull/28"},{"author":{"id":"U_kgDOCE2Lig","is_bot":false,"login":"n-ornelas","name":""},"headRefName":"n-ornelas-Wiremock-dependency","number":27,"title":"n-ornelas - Wiremock Dependency upgrade","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-13/pull/27"},{"author":{"id":"U_kgDOCML-cA","is_bot":false,"login":"amyli2027","name":"Amy Li"},"headRefName":"amyli2027-eslintupdate","number":25,"title":"Amyli2027 eslintupdate","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-13/pull/25"}]
